services:
  postgres:
    image: postgres:18.4
    container_name: task-tracker-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: tasktracker
      POSTGRES_USER: tasktracker
      POSTGRES_PASSWORD: tasktracker

    ports:
      - "5432:5432"

    volumes:
      - ./postgres_data:/var/lib/postgresql

volumes:
  postgres_data: